// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>
/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace Kelp.Test.ResourceHandling
{
	using System;
	using Kelp.ResourceHandling;

	using Machine.Specifications;

	[Subject(typeof(CodeFile)), Tags(Categories.ResourceHandling)]
	public class CodeFileTest
	{
		static CodeFileTest()
		{
			Configuration.Current.TemporaryDirectory =
				Util.MapPath(Configuration.Current.TemporaryDirectory);
		}

		~CodeFileTest()
		{
			Utilities.ClearTemporaryDirectory();
		}

		It Should_support_registered_text_based_file_extensions = () =>
		{
			CodeFile.IsFileExtensionSupported("js").ShouldBeTrue();
			CodeFile.IsFileExtensionSupported("css").ShouldBeTrue();
			CodeFile.IsFileExtensionSupported("xyz").ShouldBeFalse();
			CodeFile.IsFileExtensionSupported("jpeg").ShouldBeFalse();
		};
	}
}
