// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>
/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace Kelp.Test.ResourceHandling
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	using Kelp.ResourceHandling;
	using Machine.Specifications;

	using Microsoft.Ajax.Utilities;

	[Subject(typeof(LessCssFile)), Tags(Categories.ResourceHandling)]
	public class When_parsing_lesscss : CodeFileTest
	{
		private static LessCssFile cssFile = new LessCssFile();
		It Should_generate_valid_static_css = () =>
		{
			var file = CodeFile.Create<LessCssFile>(new CssFileConfiguration { Settings = new CssSettings
			{
				MinifyExpressions = true
			}});

			file.Load(Utilities.GetStylePath("Stylesheet1.less"));
			file.Content.ShouldContain("background:#842210");
		};
	}
}
